[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blogger = "GhtcnRfdetQQYiZX3BScjCS5bh39aTuQ4fC797khZrgi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ymsflores/solana_day1/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/blogger.json app/src/idl/blogger.json"